// Từ điển thuật ngữ Trung Cổ
export const MEDIEVAL_TERMS = {
  'Pull requests': 'Nhiệm vụ',
  Repositories: 'Vương quốc',
  Organization: 'Bang hội',
  Organizations: 'Danh Sách Bang hội',
  Issues: 'Thỉnh nguyện thư',
  Commits: 'Lời thề',
  Merged: 'Liên minh',
  Fork: 'Nhánh của vương quốc',
  Star: 'Vương miện',
  Watch: 'Gián điệp',
  Owner: 'Quốc vương',
  Admin: 'Công tước',
  Contributor: 'Kỵ sĩ',
  Member: 'Dân làng',
  Release: 'Chiếu chỉ Hoàng gia',
  Releases: 'Chiếu chỉ Hoàng gia',
  Discussion: 'Hội đồng Hoàng gia',
  Home: 'Thành trì',
  Dashboard: 'Bản đồ vương quốc',
  'Top repositories': 'Vương quốc hùng mạnh',
  'Your teams': 'Hội hiệp sĩ',
  Code: 'Bản thánh chỉ',
  Actions: 'Hành động chiến trận',
  Projects: 'Chiến dịch',
  Security: 'Bảo vệ thành trì',
  Insights: 'Lời tiên tri',
  Settings: 'Chỉnh trị vương quốc',
  Unwatch: 'Ngừng do thám',
  'Your profile': 'Chân dung Bá tước',
  'Your repositories': 'Vương quốc của người',
  'Your Copilot': 'Cố vấn hoàng gia',
  'Your projects': 'Chiến dịch của người',
  'Your stars': 'Vương miện đã ban',
  'Your gists': 'Bí kíp hoàng gia',
  'GitHub Website': 'Lâu đài GitHub',
  'GitHub Docs': 'Thư viện Hoàng gia',
  'GitHub Support': 'Sứ giả hoàng gia',
  'GitHub Community': 'Công hội lập trình',
  'Sign out': 'Thoái vị',
  'Your organizations': 'Bang hội của người',
  'Your sponsors': 'Nhà tài trợ hoàng gia',
  'Your enterprises': 'Thương hội hùng mạnh',
  'Try Enterprise': 'Dùng thử thương hội',
  'Feature preview': 'Báo cáo của Ngự sử',
  'Latest changes': 'Sắc lệnh mới nhất',
  'Explore repositories': 'Phiêu lưu khám phá vương quốc',
  Filter: 'Tìm kiếm cổ thư',
  Wiki: 'Sử thi vương quốc',
  'Popular repositories': 'KINGDOMS',
};

// Mảng các tọa độ cố định cho castles
export const CASTLE_POSITIONS = [
  { x: 25, y: 40 },
  { x: 50, y: 38 },
  { x: 76, y: 36 },
  { x: 80, y: 75 },
  { x: 12, y: 75 },
  { x: 40, y: 70 },
  { x: 20, y: 75 },
  { x: 50, y: 80 },
  { x: 80, y: 75 },
  { x: 35, y: 65 },
];

// Mảng màu sắc cho các lá cờ
export const FLAG_COLORS = [
  { primary: '#FF6B6B', secondary: '#FFE66D', accent: '#4ECDC4' },
  { primary: '#A8E6CF', secondary: '#88D8C0', accent: '#FFD93D' },
  { primary: '#6C5CE7', secondary: '#A29BFE', accent: '#FD79A8' },
  { primary: '#FD79A8', secondary: '#FDCB6E', accent: '#6C5CE7' },
  { primary: '#00B894', secondary: '#00CEC9', accent: '#55A3FF' },
  { primary: '#E17055', secondary: '#FDCB6E', accent: '#A29BFE' },
  { primary: '#FF7675', secondary: '#74B9FF', accent: '#00B894' },
  { primary: '#FDCB6E', secondary: '#E84393', accent: '#00CEC9' },
  { primary: '#74B9FF', secondary: '#FD79A8', accent: '#00B894' },
  { primary: '#55A3FF', secondary: '#FF6B6B', accent: '#FFE66D' },
];

// Cấu hình kích thước và giới hạn
export const CONFIG = {
  CONTAINER_WIDTH: 700,
  CONTAINER_HEIGHT: 430,
  SCROLLABLE_WIDTH: 900,
  SCROLLABLE_HEIGHT: 600,
  MAX_DRAG_X: 48,
  MAX_DRAG_Y: 1,
  MAX_WAIT_ATTEMPTS: 50,
  WAIT_INTERVAL: 100,
};

// CSS Selectors
export const SELECTORS = {
  PINNED_CONTAINER: '.js-pinned-items-reorder-container',
  PINNED_ITEMS: '[data-testid="pinned-items"]',
  PINNED_LIST: '.js-pinned-items-reorder-list',
  REPO_LIST: '.d-flex.flex-wrap',
  REPO_ITEMS: '.pinned-item-list-item',
};
